"""
A few functions for playing with inductive loop invariants
"""
import logging
import z3

from efmc.utils.z3_solver_utils import is_entail, is_sat, is_equiv
from efmc.utils.z3_expr_utils import get_variables, negate
from efmc.sts import TransitionSystem

logger = logging.getLogger(__name__)

def check_invariant(sts: TransitionSystem, inv: z3.ExprRef, inv_in_prime_variables: z3.ExprRef):
    """Check whether the generated invariant is correct"""
    correct = True

    # TODO: should we check the three conditions all-in-one?

    # 1. Check initiation: inv => sts.init
    if not is_entail(sts.init, inv):
        correct = False
        logger.error("Initiation check failed")
        model = get_counterexample(z3.And(sts.init, z3.Not(inv)))
        if model:
            logger.error(f"Counterexample: {model}")

    # 2. Check inductiveness: inv && sts.trans => inv'
    if not is_entail(z3.And(sts.trans, inv), inv_in_prime_variables):
        correct = False
        logger.error("Inductiveness check failed")
        model = get_counterexample(z3.And(sts.trans, inv, z3.Not(inv_in_prime_variables)))
        if model:
            logger.error(f"Counterexample: {model}")

    # 3. Check safety/suffciency: inv => sts.post
    # NOTICE: here the guard "C" is Hoare logic is "moved" to te transition relation, and we can just check is_entail(inv, sts.post) for correctness.
    if (not sts.ignore_post_cond) and (not is_entail(inv, sts.post)):
        # for some applications, we may ignore the post condition
        correct = False
        logger.error("Safety check failed")
        model = get_counterexample(z3.And(inv, z3.Not(sts.post)))
        if model:
            logger.error(f"Counterexample: {model}")

    if not correct:
        logger.debug(f"Init: {sts.init}")
        logger.debug(f"Trans: {sts.trans}")
        logger.debug(f"Post: {sts.post}")
        logger.debug(f"Inv: {inv}")
    else:
        logger.info("Invariant verification successful")
    
    return correct

def get_counterexample(formula: z3.ExprRef):
    """Get a counterexample for the given formula"""
    s = z3.Solver()
    s.add(formula)
    if s.check() == z3.sat:
        return s.model()
    return None


def weaken_invariant(sts: TransitionSystem, inv: z3.ExprRef) -> z3.ExprRef:
    """
    FIXME: the code is generated by LLM, to check
    Weaken the invariant using counterexample-guided approach:
    1. Check if current invariant is inductive
    2. If not, get counterexample and weaken the invariant
    3. Ensure the weakened invariant still implies the post-condition
    """
    if z3.is_false(inv):
        return inv
    
    inv_prime = z3.substitute(inv, list(zip(sts.variables, sts.prime_variables)))
    s = z3.Solver()
    s.add(inv)
    s.add(sts.trans)
    s.add(z3.Not(inv_prime))
    
    if s.check() == z3.sat:
        model = s.model()
        # Get values of current state variables
        state_values = []
        for var in sts.variables:
            val = model.eval(var)
            if val is not None:
                state_values.append(var >= val)
        
        # Weaken by removing the violated constraints
        weakened = z3.Or(inv, z3.And(state_values))
        
        # Ensure post-condition is still maintained
        if is_entail(weakened, sts.post):
            return weakened
    
    return inv

def strengthen_invariant(sts: TransitionSystem, inv: z3.ExprRef) -> z3.ExprRef:
    """
    FIXME: the code is generated by LLM, to check
    
    Strengthen the invariant using the following strategies:
    1. Add bounds from the post-condition
    2. Add invariant candidates from transition relation
    3. Add equality constraints from initial states
    """
    if z3.is_true(inv):
        return inv
    
    strengthened = inv
    
    # Add bounds from post-condition
    if not sts.ignore_post_cond:
        strengthened = z3.And(strengthened, sts.post)
    
    # Extract bounds from transition relation
    bounds = []
    for var in sts.variables:
        s = z3.Solver()
        s.add(sts.trans)
        s.push()
        # Try upper bound
        if s.check() == z3.sat:
            model = s.model()
            if model and model.eval(var) is not None:
                bounds.append(var <= model.eval(var))
        s.pop()
        # Try lower bound
        s.push()
        if s.check() == z3.sat:
            model = s.model()
            if model and model.eval(var) is not None:
                bounds.append(var >= model.eval(var))
        s.pop()
    
    if bounds:
        strengthened = z3.And(strengthened, *bounds)
    
    # Add equality constraints from initial states
    init_constraints = []
    s = z3.Solver()
    s.add(sts.init)
    if s.check() == z3.sat:
        model = s.model()
        for var in sts.variables:
            val = model.eval(var)
            if val is not None and z3.is_int_value(val):
                init_constraints.append(var == val)
    
    if init_constraints:
        strengthened = z3.And(strengthened, z3.Or(*init_constraints))
    
    return strengthened

