"""
FIXME: to check (this file is generated by LLM)

Implemented incremental solving using two solvers like Sally (https://github.com/SRI-CSL/sally):
  - solver1 for BMC (base case)
  - solver2 for k-induction (inductive case)

Efficient caching mechanisms
- Variable creation cache
- Substitution cache
- Leveraging @lru_cache
"""
import logging
from functools import lru_cache

import z3

from efmc.engines.kinduction.aux_invariant_generator import InvariantGenerator
from efmc.sts import TransitionSystem
from efmc.utils.verification_utils import VerificationResult

logger = logging.getLogger(__name__)


class KInductionProverInc:
    """
    k-induction prover with incremental solving and optimizations based on Sally implementation.
    """

    def __init__(self, system: TransitionSystem):
        self.sts = system
        # Initialize caches first
        self._var_at_time_cache = {}
        self._substitution_cache = {}

        self.use_bv = system.has_bv
        self.use_int = system.has_int
        self.use_real = system.has_real
        self.use_bool = system.has_bool
        if self.use_bv:
            self.bv_size = system.variables[0].sort().size()

        # Create solvers
        self.solver1 = z3.Solver()  # For BMC
        self.solver2 = z3.Solver()  # For k-induction

        # Initialize states after caches are ready
        self.init_0 = z3.substitute(self.sts.init, self.get_subs(0))
        self.post_0 = z3.substitute(self.sts.post, self.get_subs(0))
        self.solver1.add(self.init_0)

        # Initialize auxiliary invariant flag
        self.use_aux_invariant = False
        self.aux_invariant = None

    def _create_var_at_time(self, var: z3.ExprRef, t: int) -> z3.ExprRef:
        """Creates a variable at a specific time point with caching"""
        key = (str(var), t)
        if key not in self._var_at_time_cache:
            name = f"{str(var)}@{t}"
            if self.use_bv:
                result = z3.BitVec(name, self.bv_size)
            elif self.use_int:
                result = z3.Int(name)
            elif self.use_real:
                result = z3.Real(name)
            elif self.use_bool:
                result = z3.Bool(name)
            else:
                raise NotImplementedError("Unsupported variable type")
            self._var_at_time_cache[key] = result
        return self._var_at_time_cache[key]

    @lru_cache(maxsize=None)
    def get_subs(self, i: int):
        """Builds substitutions for variables at time i to i+1 with caching"""
        if i not in self._substitution_cache:
            subs = []
            for curr, next_var in zip(self.sts.variables, self.sts.prime_variables):
                subs.append((curr, self._create_var_at_time(curr, i)))
                subs.append((next_var, self._create_var_at_time(curr, i + 1)))
            self._substitution_cache[i] = subs
        return self._substitution_cache[i]

    def _add_transition_at_k(self, k: int):
        """Incrementally adds transition relation at step k"""
        trans_k = z3.substitute(self.sts.trans, self.get_subs(k))
        self.solver1.add(trans_k)
        self.solver2.add(trans_k)

    def _add_property_at_k(self, k: int):
        """Adds property constraint at step k"""
        prop_k = z3.substitute(self.sts.post, self.get_subs(k))
        return prop_k

    def solve(self, max_k: int, min_k: int = 0) -> VerificationResult:
        """
        Performs k-induction proof using incremental solving following Sally's approach.

        Args:
            max_k: Maximum bound to check
            min_k: Minimum bound before checking inductive step
            
        Returns:
            VerificationResult: Object containing verification result and related data
        """
        if self.use_aux_invariant:
            inv_gen = InvariantGenerator(self.sts)
            self.aux_invariant = inv_gen.generate_via_ef()
            self.use_aux_invariant = not z3.is_true(self.aux_invariant)

        print(f"Checking property {self.sts.post}...")

        for k in range(max_k):
            # Base case (BMC)
            logger.debug(f"[BMC] Checking bound {k}...")
            self.solver1.push()
            prop_k = self._add_property_at_k(k)
            self.solver1.add(z3.Not(prop_k))

            if self.solver1.check() == z3.sat:
                print(f"--> Bug found at step {k}")
                model = self.solver1.model()
                return VerificationResult(False, None, model)
            self.solver1.pop()

            # Inductive case
            if k >= min_k:
                logger.debug(f"[K-IND] Checking bound {k}...")
                self.solver2.push()

                # Add k-hypothesis
                for i in range(k):
                    self.solver2.add(self._add_property_at_k(i))

                # Add auxiliary invariants if available
                if self.use_aux_invariant:
                    for i in range(k + 1):
                        self.solver2.add(z3.substitute(self.aux_invariant, self.get_subs(i)))

                # Check inductive step
                self.solver2.add(z3.Not(prop_k))
                if self.solver2.check() == z3.unsat:
                    print(f"--> System proved safe at k={k}")
                    # Create an invariant from the k-induction proof
                    invariant = self.sts.post
                    return VerificationResult(True, invariant)
                self.solver2.pop()

            # Prepare for next iteration
            if k < max_k - 1:
                self._add_transition_at_k(k)

        return VerificationResult(False, None, None)


def main():
    x, y, _p_x, _p_y = z3.Reals('x y x! y!')
    init = z3.And(x == 0, y == 8)
    trans = z3.Or(z3.And(x < 8, y <= 8, _p_x == x + 2, _p_y == y - 2), z3.And(x == 8, _p_x == 0, y == 0, _p_y == 8))
    post = z3.Not(z3.And(x == 0, y == 0))  # Is valid.
    all_vars = [x, y, _p_x, _p_y]

    from efmc.sts import TransitionSystem
    sts = TransitionSystem()

    sts.from_z3_cnts([all_vars, init, trans, post])
    pp = KInductionProverInc(sts)
    res = pp.solve(k=20)


if __name__ == '__main__':
    main()
