"""
FIXME: this file is generated by LLM
  This file is very likely to be buggy
"""

from dataclasses import dataclass
from typing import Dict, Optional

import z3

from efmc.sts import TransitionSystem


@dataclass
class Interval:
    """Represents an interval abstract domain element [lower, upper]"""
    lower: Optional[int] = None  # None represents negative infinity
    upper: Optional[int] = None  # None represents positive infinity

    def __str__(self):
        lower = "-∞" if self.lower is None else str(self.lower)
        upper = "∞" if self.upper is None else str(self.upper)
        return f"[{lower}, {upper}]"


class AbstractInterpreter:
    def __init__(self, ts: TransitionSystem):
        self.ts = ts
        self.invariant_map: Dict[z3.ExprRef, Interval] = {}

    def analyze(self) -> Dict[z3.ExprRef, Interval]:
        """Main analysis function that computes invariants"""
        # Initialize invariants from initial conditions
        self._init_invariants()

        # Fixpoint computation
        changed = True
        while changed:
            changed = False
            new_invariants = self._analyze_transition()

            # Update invariants and check for changes
            for var, new_interval in new_invariants.items():
                if not self._intervals_equal(self.invariant_map[var], new_interval):
                    changed = True
                    self.invariant_map[var] = self._join_intervals(
                        self.invariant_map[var],
                        new_interval
                    )

        return self.invariant_map

    def _init_invariants(self):
        """Initialize invariants from initial conditions"""
        solver = z3.Solver()
        solver.add(self.ts.init)

        # Initialize with top intervals
        for var in self.ts.variables:
            self.invariant_map[var] = Interval()

        # Refine intervals based on initial conditions
        if solver.check() == z3.sat:
            model = solver.model()
            for var in self.ts.variables:
                if var in model:
                    val = model[var].as_long()
                    self.invariant_map[var] = Interval(val, val)

    def _analyze_transition(self) -> Dict[z3.ExprRef, Interval]:
        """Analyze one step of the transition relation"""
        new_invariants = {}
        solver = z3.Solver()
        solver.add(self.ts.trans)

        # Add current invariants to solver
        for var, interval in self.invariant_map.items():
            if interval.lower is not None:
                solver.add(var >= interval.lower)
            if interval.upper is not None:
                solver.add(var <= interval.upper)

        # Compute new intervals for prime variables
        for prime_var in self.ts.prime_variables:
            new_invariants[prime_var] = self._compute_var_bounds(solver, prime_var)

        # Convert prime variable intervals to non-prime variables
        result = {}
        for i, var in enumerate(self.ts.variables):
            result[var] = new_invariants[self.ts.prime_variables[i]]

        return result

    def _compute_var_bounds(self, solver: z3.Solver, var: z3.ExprRef) -> Interval:
        """Compute bounds for a single variable"""
        interval = Interval()

        # Find lower bound
        if solver.check() == z3.sat:
            optimizer = z3.Optimize()
            optimizer.add(solver.assertions())
            objective = optimizer.minimize(var)
            if optimizer.check() == z3.sat:
                model = optimizer.model()
                if var in model:
                    interval.lower = model[var].as_long()

        # Find upper bound
        if solver.check() == z3.sat:
            optimizer = z3.Optimize()
            optimizer.add(solver.assertions())
            objective = optimizer.maximize(var)
            if optimizer.check() == z3.sat:
                model = optimizer.model()
                if var in model:
                    interval.upper = model[var].as_long()

        return interval

    def _intervals_equal(self, int1: Interval, int2: Interval) -> bool:
        """Check if two intervals are equal"""
        return int1.lower == int2.lower and int1.upper == int2.upper

    def _join_intervals(self, int1: Interval, int2: Interval) -> Interval:
        """Compute the join (least upper bound) of two intervals"""
        lower = None
        if int1.lower is not None and int2.lower is not None:
            lower = min(int1.lower, int2.lower)

        upper = None
        if int1.upper is not None and int2.upper is not None:
            upper = max(int1.upper, int2.upper)

        return Interval(lower, upper)

    def get_invariant_formula(self) -> z3.ExprRef:
        """Convert computed invariants to a Z3 formula"""
        conjuncts = []
        for var, interval in self.invariant_map.items():
            if interval.lower is not None:
                conjuncts.append(var >= interval.lower)
            if interval.upper is not None:
                conjuncts.append(var <= interval.upper)
        return z3.And(conjuncts) if conjuncts else z3.BoolVal(True)
