"""
FIXME: generated by LLM, to be reviewed

For examples, 
1. the parity domain checks if bit vector values are even or odd when interpreted as unsigned integers.
2. The bit masks domain tracks must-information about individual bits (0, 1, or unknown).
"""

from efmc.engines.ef.templates.abstract_template import TemplateType, Template
from efmc.sts import TransitionSystem
from efmc.utils import get_variables
import z3


class ParityTemplate(Template):
    def __init__(self, ts: TransitionSystem):
        super().__init__(ts)
        self.template_type = TemplateType.PARITY
    
    def add_template_vars(self):
        self.template_vars = get_variables(self.sts.variables)
        # Add a boolean variable for each program variable to track parity
        self.parity_vars = {var: z3.Bool(f"parity_{var}") for var in self.template_vars}

    def get_additional_cnts_for_template_vars(self):
        return z3.BoolVal(True)
    
    def add_template_cnts(self):
        cnts = []
        for var in self.template_vars:
            # For each variable, add constraint that parity_var is True iff variable is even
            var_val = self.sts.variables[var]
            if z3.is_bv(var_val):
                cnts.append(self.parity_vars[var] == (z3.URem(var_val, 2) == 0))
        return z3.And(cnts) if cnts else z3.BoolVal(True)


class BitMasksTemplate(Template):
    def __init__(self, ts: TransitionSystem):
        super().__init__(ts)
        self.template_type = TemplateType.BITMASKS
        
    def add_template_vars(self):
        self.template_vars = get_variables(self.sts.variables)
        self.bit_vars = {}
        # For each variable and each bit position, create two boolean variables
        # to represent must-be-0 and must-be-1
        for var in self.template_vars:
            var_val = self.sts.variables[var]
            if z3.is_bv(var_val):
                bw = var_val.size()
                self.bit_vars[var] = [(z3.Bool(f"must0_{var}_{i}"), 
                                     z3.Bool(f"must1_{var}_{i}")) 
                                    for i in range(bw)]

    def get_additional_cnts_for_template_vars(self):
        cnts = []
        # A bit cannot be must-be-0 and must-be-1 at the same time
        for var in self.bit_vars:
            for must0, must1 in self.bit_vars[var]:
                cnts.append(z3.Not(z3.And(must0, must1)))
        return z3.And(cnts) if cnts else z3.BoolVal(True)
    
    def add_template_cnts(self):
        cnts = []
        for var in self.bit_vars:
            var_val = self.sts.variables[var]
            for i, (must0, must1) in enumerate(self.bit_vars[var]):
                # Extract i-th bit
                bit_i = z3.Extract(i, i, var_val)
                # If must0 is true, bit must be 0
                cnts.append(z3.Implies(must0, bit_i == 0))
                # If must1 is true, bit must be 1
                cnts.append(z3.Implies(must1, bit_i == 1))
        return z3.And(cnts) if cnts else z3.BoolVal(True)
